app:
    endpoint: /api/customer
    port: 8080
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: "airline"
swagger:
  name: Customer Microservice API
  api:
    title: Customer API Swagger 
    version: 1.0.0
    description: API documentation for Customer Microservice
    base-package: com.airline.customer
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true