app:
    endpoint: /api/customer
spring:
  data:
    mongodb:
      uri: "mongodb://user:secret@mongoserver1.example.com:27017,mongoserver2.example.com:23456/test"
swagger:
  name: Customer Microservice API
  api:
    title: Customer API Swagger 
    version: 1.0.0
    description: API documentation for Customer Microservice
    base-package: com.airline.customer
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true